<?php
defined('_RONIN') or die;
$app = array(
    'nav' => array(
        'home' => array(
            'alias' => 'home',
            'title' => 'Home',
            'view' => 'default',
            'modal' => false,
        ),
        'rfh' => array(
            'alias' => 'rfh',
            'title' => 'Ronin Form Handler',
            'view' => 'rfh',
            'modal' => false,
        ),
        'admin' => array(
            'alias' => 'admin',
            'title' => 'Admin',
            'view' => 'admin',
            'modal' => false,
        ),
        'item' => array(
            'alias' => 'item',
            'title' => 'Item',
            'view' => 'item',
            'modal' => true,
        ),
    ),
    'users' => array(
        'public' => array(
            'id' => '1',
            'alias' => 'public',
            'title' => 'Public User',
            'name' => 'Anonymous',
            'password' => '7215ee9c7d9dc229d2921a40e899ec5f',
            'ordering' => '1',
            'group' => 'public',
            'state' => '1',
        ),
        'registered' => array(
            'id' => '3',
            'alias' => 'registered',
            'title' => 'Registered User',
            'name' => 'Usuario registrado',
            'password' => '31d21508dcf769c00f334d739ccd1bc4',
            'ordering' => '2',
            'group' => 'registered',
            'state' => '1',
        ),
        'povuv' => array(
            'id' => '3',
            'alias' => 'povuv',
            'title' => 'Povuv',
            'name' => 'Roberto García',
            'password' => 'a6ecd832789bd50dce0cdb5a94274505',
            'ordering' => '3',
            'group' => 'superadmin',
            'state' => '1',
        ),
    ),
    'user-groups' => array(
        'public' => array(
            'id' => '1',
            'alias' => 'public',
            'title' => 'Public',
            'name' => 'Grupo de usuarios visitantes',
            'ordering' => '1',
            'level' => '0',
            'state' => '1',
        ),
        'registered' => array(
            'id' => '2',
            'alias' => 'registered',
            'title' => 'Registered',
            'name' => 'Grupo de usuarios registrados',
            'ordering' => '2',
            'level' => '1',
            'state' => '1',
        ),
        'editor' => array(
            'id' => '3',
            'alias' => 'editor',
            'title' => 'Editor',
            'name' => 'Grupo de usuarios editores',
            'ordering' => '3',
            'level' => '2',
            'state' => '1',
        ),
        'manager' => array(
            'id' => '4',
            'alias' => 'manager',
            'title' => 'Manager',
            'name' => 'Grupo de usuarios gerentes',
            'ordering' => '4',
            'level' => '3',
            'state' => '1',
        ),
        'admin' => array(
            'id' => '5',
            'alias' => 'admin',
            'title' => 'Admin',
            'name' => 'Grupo de usuarios administradores',
            'ordering' => '5',
            'level' => '4',
            'state' => '1',
        ),
        'superadmin' => array(
            'id' => '6',
            'alias' => 'superadmin',
            'title' => 'Superadmin',
            'name' => 'Grupo de usuarios superadministradores',
            'ordering' => '6',
            'level' => '5',
            'state' => '1',
        ),
    ),
    'data-fields'   => array(
        'id' => array(
            'id' => '1',
            'alias' => 'id',
            'type' => 'text',
            'title' => 'Id',
            'name' => 'id',
            'value' => 'auto',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '',
            'readonly' => '1',
            'ordering' => '1',
            'state' => '1',
            'xreference' => 'row-start',
        ),
        'title' => array(
            'id' => '2',
            'alias' => 'id',
            'type' => 'text',
            'title' => 'Title',
            'name' => 'title',
            'value' => '',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '2',
            'readonly' => '',
            'ordering' => '11',
            'state' => '1',
            'xreference' => 'row-start',
        ),
        'alias' => array(
            'id' => '3',
            'alias' => 'id',
            'type' => 'text',
            'title' => 'Alias',
            'name' => 'alias',
            'value' => '',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '',
            'readonly' => '',
            'ordering' => '2',
            'state' => '1',
            'xreference' => 'row-end',
        ),
        'content' => array(
            'id' => '4',
            'alias' => 'id',
            'type' => 'textarea',
            'title' => 'Content',
            'name' => 'content',
            'value' => '',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '1',
            'readonly' => '',
            'ordering' => '12',
            'state' => '1',
            'xreference' => 'row-end',
        ),
        'state' => array(
            'id' => '5',
            'alias' => 'id',
            'type' => 'toggle',
            'title' => 'State',
            'name' => 'state',
            'value' => '1',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '1',
            'readonly' => '',
            'ordering' => '32',
            'state' => '1',
            'xreference' => 'row-end',
        ),
        'ordering' => array(
            'id' => '6',
            'alias' => 'id',
            'type' => 'text',
            'title' => 'Ordering',
            'name' => 'ordering',
            'value' => '99',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '1',
            'readonly' => '',
            'ordering' => '31',
            'state' => '1',
            'xreference' => '',
        ),
        'type' => array(
            'id' => '7',
            'alias' => 'id',
            'type' => 'text',
            'title' => 'Type',
            'name' => 'type',
            'value' => 'item',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '',
            'readonly' => '',
            'ordering' => '20',
            'state' => '1',
            'xreference' => 'row-start',
        ),
        'xreference' => array(
            'id' => '8',
            'alias' => 'id',
            'type' => 'text',
            'title' => 'xreference',
            'name' => 'xreference',
            'value' => '',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '',
            'readonly' => '',
            'ordering' => '21',
            'state' => '1',
            'xreference' => 'row-end',
        ),
        'access' => array(
            'id' => '9',
            'alias' => 'id',
            'type' => 'access',
            'title' => 'Access',
            'name' => 'access',
            'value' => '0',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '',
            'readonly' => '',
            'ordering' => '30',
            'state' => '1',
            'xreference' => 'row-start',
        ),
        'featured' => array(
            'id' => '10',
            'alias' => 'id',
            'type' => 'toggle',
            'title' => 'Featured',
            'name' => 'featured',
            'value' => '0',
            'Placeholder' => '',
            'class' => '',
            'style' => '',
            'required' => '',
            'readonly' => '',
            'ordering' => '40',
            'state' => '0',
            'xreference' => '',
        ),
    ),
);
return $app;
?>
